# Generated by Django 4.2.16 on 2024-11-20 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_alter_product_name_alter_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="address",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "Адрес не может быть пустым."
                    ),
                    django.core.validators.RegexValidator(
                        "^[\\w\\s,-]+$", "Адрес содержит некорректные символы."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="person",
            field=models.CharField(
                max_length=200,
                validators=[
                    django.core.validators.MinLengthValidator(
                        1, "Имя не может быть пустым."
                    ),
                    django.core.validators.RegexValidator(
                        "^[a-zA-Zа-яА-ЯёЁ\\s]+$", "Имя должно содержать только буквы."
                    ),
                ],
            ),
        ),
    ]
